name: Sync Icons

on:
  schedule:
    - cron: 0 0 * * 2,4,6
  workflow_dispatch:

jobs:
  sync:
    name: Sync Icons
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
      - name: Install Packages
        run: npm ci
      - name: Generate token
        id: generate-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.GRAVITY_UI_APP_ID }}
          private-key: ${{ secrets.GRAVITY_UI_APP_PRIVATE_KEY }}
      - name: Download SVG Files
        run: npm run src:download
        env:
          FIGMA_TOKEN: ${{ secrets.FIGMA_TOKEN }}
          FIGMA_FILE: ${{ secrets.FIGMA_FILE }}
          FIGMA_PAGE: ${{ secrets.FIGMA_PAGE }}
      - name: Create TS/JS Files
        run: npm run src:icons
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ steps.generate-token.outputs.token }}
          commit-message: 'feat: sync icons'
          branch: sync-icons
          delete-branch: true
          reviewers: amje
          title: 'feat: sync icons'
          body: ''
